package com.dekler.destructionfury.map;

public enum AnimationEnum
{
	WALK_UP, WALK_DOWN, WALK_LEFT, WALK_RIGHT, ATTACK_UP, ATTACK_DOWN, ATTACK_LEFT, ATTACK_RIGHT, STUCK_RIGHT, STUCK_LEFT, STUCK_UP,STUCK_DOWN;
}
